// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNnm8Pn4mBjdhHWz-ReF1NPOe_yMTgkb8',
    appId: '1:926443017819:web:a7f2e33a3a8a4bd7b6917e',
    messagingSenderId: '926443017819',
    projectId: 'yumslice-2bab2',
    authDomain: 'yumslice-2bab2.firebaseapp.com',
    storageBucket: 'yumslice-2bab2.firebasestorage.app',
    measurementId: 'G-4WKC6ESKHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADr8msZQ2tqTKR0FsVGs89wDzuU8E53LE',
    appId: '1:926443017819:android:a0cb82bbabe69b45b6917e',
    messagingSenderId: '926443017819',
    projectId: 'yumslice-2bab2',
    storageBucket: 'yumslice-2bab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5iRa-fZk1YEcDa1OE49UA268R3Rdw-I',
    appId: '1:926443017819:ios:a4924534dee220f9b6917e',
    messagingSenderId: '926443017819',
    projectId: 'yumslice-2bab2',
    storageBucket: 'yumslice-2bab2.firebasestorage.app',
    iosBundleId: 'com.cakes.cakesStoreFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu5iRa-fZk1YEcDa1OE49UA268R3Rdw-I',
    appId: '1:926443017819:ios:a4924534dee220f9b6917e',
    messagingSenderId: '926443017819',
    projectId: 'yumslice-2bab2',
    storageBucket: 'yumslice-2bab2.firebasestorage.app',
    iosBundleId: 'com.cakes.cakesStoreFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNnm8Pn4mBjdhHWz-ReF1NPOe_yMTgkb8',
    appId: '1:926443017819:web:b9053d8f5322c078b6917e',
    messagingSenderId: '926443017819',
    projectId: 'yumslice-2bab2',
    authDomain: 'yumslice-2bab2.firebaseapp.com',
    storageBucket: 'yumslice-2bab2.firebasestorage.app',
    measurementId: 'G-KTEN2V9P98',
  );
}
